#pragma once

typedef unsigned __int8 KNDBG_UINT8;
typedef unsigned __int32 KNDBG_UINT32;
typedef unsigned __int64 KNDBG_UINT64;

#define KNDBG_DEVICE_NAME L"\\Device\\KnLiveDbg"
#define KNDBG_DOS_DEVICE_NAME L"\\DosDevices\\KnLiveDbg"
#define KNDBG_USER_DEVICE_NAME L"\\\\.\\KnLiveDbg"
#define KNDBG_SERVICE_NAME L"KnLiveDbg"
#define KNDBG_DISPLAY_NAME L"Kn Live Debug Driver"

#define KNDBG_ABI_VERSION 6u
#define KNDBG_MAX_TRANSFER_SIZE (1024u * 1024u)
#define KNDBG_WRITE_ACK_MAGIC 0x4B4E444247574F4Full

#define KNDBG_TRANSLATE_FLAG_CURRENT_CR3 0x00000001u
#define KNDBG_TRANSLATE_FLAG_LARGE_PAGE 0x00000002u
#define KNDBG_TRANSLATE_FLAG_LA57_ACTIVE 0x00000004u
#define KNDBG_TRANSLATE_FLAG_PROCESS_DTB 0x00000008u

#define KNDBG_VERSION_FLAG_SINGLE_CONTROLLER 0x00000001u
#define KNDBG_VERSION_FLAG_LA57_ACTIVE 0x00000002u

#define KNDBG_SESSION_FLAG_OWNER_ACTIVE 0x00000001u
#define KNDBG_SESSION_FLAG_WRITE_ENABLED 0x00000002u

#define KNDBG_PROCESS_FLAG_USER_DTB_AVAILABLE 0x00000001u

#ifndef CTL_CODE
#define CTL_CODE(DeviceType, Function, Method, Access) \
    (((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method))
#endif

#ifndef FILE_DEVICE_UNKNOWN
#define FILE_DEVICE_UNKNOWN 0x00000022
#endif

#ifndef METHOD_BUFFERED
#define METHOD_BUFFERED 0
#endif

#ifndef FILE_ANY_ACCESS
#define FILE_ANY_ACCESS 0
#endif

#ifndef FILE_READ_DATA
#define FILE_READ_DATA 0x0001
#endif

#ifndef FILE_WRITE_DATA
#define FILE_WRITE_DATA 0x0002
#endif

#define IOCTL_KNDBG_GET_VERSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KNDBG_READ_VIRTUAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_KNDBG_WRITE_VIRTUAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_KNDBG_SET_WRITE_MODE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_KNDBG_QUERY_ADDRESS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_KNDBG_TRANSLATE_VIRTUAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_KNDBG_READ_PHYSICAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_KNDBG_WRITE_PHYSICAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_KNDBG_GET_SESSION_STATUS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_KNDBG_RESOLVE_PROCESS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80A, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_KNDBG_FLUSH_VIRTUAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80B, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_KNDBG_SET_PROCESS_PROTECTION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80C, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

// Known _EPROCESS.Protection byte values. The PS_PROTECTION struct packs
// Signer (high nibble) over Audit (bit 3) over Type (bits 0..2).
//   Type:   0 = None, 1 = ProtectedLight (PPL), 2 = Protected
//   Signer: 3 = Antimalware, 4 = Lsa, 5 = Windows, 6 = WinTcb, 7 = WinSystem
// PPL Antimalware: Signer=3, Audit=0, Type=1 -> (3<<4) | 1 = 0x31.
#define KNDBG_PROTECTION_NONE              0x00
#define KNDBG_PROTECTION_PPL_ANTIMALWARE   0x31
#define KNDBG_PROTECTION_PPL_LSA           0x41
#define KNDBG_PROTECTION_PPL_WINDOWS       0x51
#define KNDBG_PROTECTION_PPL_WINTCB        0x61

#pragma pack(push, 8)

typedef struct _KNDBG_VERSION_RESPONSE
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 AbiVersion;
    KNDBG_UINT32 DriverMajor;
    KNDBG_UINT32 DriverMinor;
    KNDBG_UINT32 MaxTransferSize;
    KNDBG_UINT32 Flags;
} KNDBG_VERSION_RESPONSE;

typedef struct _KNDBG_SESSION_STATUS_RESPONSE
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT32 OwnerPid;
    KNDBG_UINT32 CurrentPid;
    KNDBG_UINT32 OpenHandleCount;
    KNDBG_UINT32 Reserved;
} KNDBG_SESSION_STATUS_RESPONSE;

typedef struct _KNDBG_PROCESS_RESOLVE_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT32 ProcessId;
    KNDBG_UINT32 DirectoryTableBaseOffset;
    KNDBG_UINT32 UserDirectoryTableBaseOffset;
    KNDBG_UINT32 Reserved;
} KNDBG_PROCESS_RESOLVE_REQUEST;

typedef struct _KNDBG_PROCESS_RESOLVE_RESPONSE
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT32 ProcessId;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Eprocess;
    KNDBG_UINT64 DirectoryTableBase;
    KNDBG_UINT64 UserDirectoryTableBase;
} KNDBG_PROCESS_RESOLVE_RESPONSE;

typedef struct _KNDBG_READ_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Address;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Flags;
    KNDBG_UINT8 Data[1];
} KNDBG_READ_REQUEST;

typedef struct _KNDBG_WRITE_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Address;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Flags;
    KNDBG_UINT64 Acknowledge;
    KNDBG_UINT8 Data[1];
} KNDBG_WRITE_REQUEST;

typedef struct _KNDBG_WRITE_MODE_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 EnableWrite;
    KNDBG_UINT64 Acknowledge;
} KNDBG_WRITE_MODE_REQUEST;

typedef struct _KNDBG_ADDRESS_QUERY_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Address;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Flags;
} KNDBG_ADDRESS_QUERY_REQUEST;

typedef struct _KNDBG_ADDRESS_QUERY_RESPONSE
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 IsReadable;
    KNDBG_UINT32 IsWritable;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Address;
    KNDBG_UINT32 RequestedLength;
    KNDBG_UINT32 ProbedLength;
} KNDBG_ADDRESS_QUERY_RESPONSE;

typedef struct _KNDBG_TRANSLATE_VIRTUAL_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT64 DirectoryTableBase;
    KNDBG_UINT64 VirtualAddress;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Reserved;
} KNDBG_TRANSLATE_VIRTUAL_REQUEST;

typedef struct _KNDBG_TRANSLATE_VIRTUAL_RESPONSE
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT64 DirectoryTableBase;
    KNDBG_UINT64 VirtualAddress;
    KNDBG_UINT64 PhysicalAddress;
    KNDBG_UINT64 PageSize;
    KNDBG_UINT64 PageOffset;
    KNDBG_UINT64 PageBytes;
    KNDBG_UINT32 RequestedLength;
    KNDBG_UINT32 TranslatedLength;
    KNDBG_UINT32 PagingLevels;
    KNDBG_UINT32 Reserved2;
    KNDBG_UINT64 Pml4e;
    KNDBG_UINT64 Pml5e;
    KNDBG_UINT64 Pdpte;
    KNDBG_UINT64 Pde;
    KNDBG_UINT64 Pte;
    KNDBG_UINT64 Pml5eAddress;
    KNDBG_UINT64 Pml4eAddress;
    KNDBG_UINT64 PdpteAddress;
    KNDBG_UINT64 PdeAddress;
    KNDBG_UINT64 PteAddress;
} KNDBG_TRANSLATE_VIRTUAL_RESPONSE;

typedef struct _KNDBG_PHYSICAL_READ_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT64 PhysicalAddress;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT8 Data[1];
} KNDBG_PHYSICAL_READ_REQUEST;

typedef struct _KNDBG_PHYSICAL_WRITE_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT64 PhysicalAddress;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Acknowledge;
    KNDBG_UINT8 Data[1];
} KNDBG_PHYSICAL_WRITE_REQUEST;

typedef struct _KNDBG_FLUSH_VIRTUAL_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT64 VirtualAddress;
    KNDBG_UINT32 Length;
    KNDBG_UINT32 Reserved;
    KNDBG_UINT64 Acknowledge;
} KNDBG_FLUSH_VIRTUAL_REQUEST;

typedef struct _KNDBG_SET_PROCESS_PROTECTION_REQUEST
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT32 ProcessId;
    KNDBG_UINT32 ProtectionFieldOffset; // offset of PS_PROTECTION inside _EPROCESS (PDB-derived)
    KNDBG_UINT8  NewProtection;         // raw PS_PROTECTION byte to install
    KNDBG_UINT8  Reserved[3];
    KNDBG_UINT64 Acknowledge;           // must equal KNDBG_WRITE_ACK_MAGIC
} KNDBG_SET_PROCESS_PROTECTION_REQUEST;

typedef struct _KNDBG_SET_PROCESS_PROTECTION_RESPONSE
{
    KNDBG_UINT32 Size;
    KNDBG_UINT32 Flags;
    KNDBG_UINT32 ProcessId;
    KNDBG_UINT32 ProtectionFieldOffset;
    KNDBG_UINT8  OldProtection;
    KNDBG_UINT8  NewProtection;
    KNDBG_UINT8  ReadBackProtection;
    KNDBG_UINT8  Reserved;
    KNDBG_UINT64 EprocessAddress;
} KNDBG_SET_PROCESS_PROTECTION_RESPONSE;

#pragma pack(pop)
